[tools]
bun = "latest"
node = "lts"
uv = "latest"
"aqua:spinel-coop/rv" = "latest"
java = "lts"
go = "latest"
elixir = "1.19-otp-27"
rust = "latest"
dotnet = "latest"

lua-language-server = "latest"
tombi = "latest"
marksman = "latest"
tree-sitter = "latest"

"npm:npm" = "latest"
# "npm:yarn" = "latest"
# "npm:typescript" = "latest"
# "npm:typescript-language-server" = "latest"
# "npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
"npm:@github/copilot-language-server" = "latest"
"npm:marked" = "latest"
"npm:opencode-ai" = "latest"
"npm:@biomejs/biome" = "latest"
"npm:tree-sitter-cli" = "latest"
"npm:@mariozechner/pi-coding-agent" = "latest"

# "github:iwe-org/iwe" = "latest"
# "github:git-town/git-town" = "latest"
# "github:thomasschafer/scooter" = "latest"
# "github:elixir-lang/expert" = "latest"

# "pipx:pyinfra" = "latest"
# "pipx:honcho" = "latest"

# "go:github.com/air-verse/air" = "latest"
# "go:github.com/sqlc-dev/sqlc/cmd/sqlc" = "latest"
# "go:github.com/golang-migrate/migrate/v4/cmd/migrate" = { version = "latest", tags = "postgres" }
# "go:github.com/melkeydev/go-blueprint" = "latest"
# "go:golang.org/x/tools/gopls" = "latest"
# "go:golang.org/x/tools/cmd/goimports" = "latest"
# "go:github.com/golangci/golangci-lint/v2/cmd/golangci-lint" = "latest"
# "go:github.com/nametake/golangci-lint-langserver" = "latest"
# "go:github.com/go-delve/delve/cmd/dlv" = "latest"

neovim = "latest"
tmux = "latest"
ripgrep = "latest"
fd = "latest"
btop = "latest"
# lazygit = "latest"
# fzf = "latest"
# eza = "latest"
# fastfetch = "latest"
# starship = "latest"

[settings.pipx]
uvx = true

[settings.npm]
package_manager = "bun"
