openai-api-base: https://api.githubcopilot.com
model:           claude-sonnet-4
weak-model:      gpt-4.1
show-model-warnings: false
dark-mode: true
code-theme: one-dark
attribute-author: false
attribute-commiter: false
attribute-co-authored-by: false
