font=ZedMono Nerd Font:size=15.4
font-bold=ZedMono Nerd Font:size=15.4:weight=bold
font-italic=ZedMono Nerd Font:size=15.4
font-bold-italic=ZedMono Nerd Font:size=15.4:weight=bold
bold-text-in-bright=no
dpi-aware=yes
#initial-window-mode=maximized
pad=0x0 center
underline-thickness=0px

[colors-dark]
alpha=0.90

[csd]
size=0
preferred=server
hide-when-maximized=yes

[scrollback]
lines = 100000

[mouse]
hide-when-typing=yes

[main]
include=~/.config/foot/themes/noctalia
