[ids]
*

[main]

# home row mods
# a = overloadt(meta, a, 200)
# s = overloadt(shift, s, 200)
# d = overloadt(alt, d, 200)
# f = overloadt(control, f, 200)
# j = overloadt(control, j, 200)
# k = overloadt(alt, k, 200)
# l = overloadt(shift, l, 200)
# ; = overloadt(meta, ;, 200)
# v = overloadt(altgr, v, 200)
# m = overloadt(altgr, m, 200)
# leftshift = oneshot(shift)
# rightshift = oneshot(shift)

capslock = overload(capslock, esc)

[capslock]
h = left
j = down
k = up
l = right
p = print
backspace = delete
' = `
n = ~
, = volumedown
. = volumeup
[ = previoussong
] = nextsong
enter = playpause
m = mute
mute = micmute

[capslock+C]
h = C-left
j = C-down
k = C-up
l = C-right
m = micmute
