onboarding = false
[update]
channel = "stable"
version_check = true
manifest_check = true


[ui]
pane_gaps = false
hide_tab_bar_when_single_tab = true
tab_bar_position = "bottom"
sidebar_collapsed_mode = "hidden"

[ui.toast]
delivery = "herdr"
