accent = "#fff59b"
panel_bg = "reset"
sidebar_bg = "reset"
active_row_bg = "#17173c"
selection_bg = "#1c1c4b"
surface0 = "#17173c"
surface1 = "#1c1c4b"
surface_dim = "#040411"
overlay0 = "#51589b"
overlay1 = "#7c80b4"
text = "#f3edf7"
subtext0 = "#7c80b4"
mauve = "#fd4663"
green = "#9bfece"
yellow = "#fff59b"
red = "#fd4663"
blue = "#a9aefe"
teal = "#9bfece"
peach = "#fd8446"
